Displaylayout scene combine
joelsiks/admirals pull request #102
Opened 2023-12-04 16:50 UTC by joelsiks

A large PR (again).

The main reason why the work in this PR was necessary is because `DisplayLayout` and `Scene` shared a significant portion of common functionality (which they should) and thus much code were written in several places (bad because changes require [shotgun surgery](https://refactoring.guru/smells/shotgun-surgery)). This has been solved by creating an interface (class) called `IDisplayLayer`, which `DisplayLayout`, `Scene` and `Menu` now inherits from.

To support this abstraction in the we've removed the limitation of having one `DisplayLayout` and instead support multiple layers, stored in a map indexed by a `size_t`. Following this, `SetAndGetDisplayLayout` has been removed in favor of more general `AddLayer/RemoveLayer/LayerIsActive/ToggleLayer/ActivateLayer/DeactivateLayer` that work on specific layers using a `size_t` index.

The files `UI/Data.{hpp, cpp}` have also been created to store "shared" data types/utility between UI classes/functions.

The `scene::` namespace has been removed.

Fixes #96

2023-12-04 17:57 UTC, joelsiks commented
Do you think that keeping the `m_scene` and `SetAndGetScene` is a good choice or should we do something similar to what I've done to the new layer system for scenes. However, for scenes only one scene would be active at a time so instead of keeping track of set as we do for layers, one might just use a `size_t m_activeSceneIdx` variable instead.

2023-12-05 09:45 UTC, JoXW100 commented
> Do you think that keeping the `m_scene` and `SetAndGetScene` is a good choice or should we do something similar to what I've done to the new layer system for scenes. However, for scenes only one scene would be active at a time so instead of keeping track of set as we do for layers, one might just use a `size_t m_activeSceneIdx` variable instead.

I think we should not store references to all scenes in the engine, for larger projects it might become relevant to remove a scene from memory. Keeping multiple layers in the scene is valid because we can render multiple of them however, since we will never want to render multiple scenes at once we will not see much benefit from storing a reference to them in the engine.

2023-12-05 10:02 UTC, JoXW100 requested changes
Works great, i have noted some mistakes that should be addressed.

2023-12-05 14:29 UTC, JoXW100 approved these changes

2023-12-05 14:30 UTC, merged