Multiple General Improvements
joelsiks/admirals pull request #119
Opened 2023-12-06 13:21 UTC by JoXW100

Fixes #81 
Fixes #114 

- Implemented `NavMesh` to store navigation data between pathfinding.
- Implemented `TresureIsland` gameobject and spawned them dynamically 
- Made `Base` into a type of ship to simplify targeting
- Added spawn locations to `ShipInfo` to reduce duplication of hard-coded positions, and to support multiple spawns
- Fixed error in the win screen causing crash
- Improved pathfinding
- Added ship debug view of the navmesh.
- Made `DataObject` methods and constructors into `constexpr`
- Added text scaling

From #120 
- Improved server tickrate
- Added cooldowns to ship movement and attacks affected by their speed.

2023-12-06 21:40 UTC, joelsiks commented
Just want to add that some of the changes here could have been made into their own pull requests since this one is very large (42 files changed). For example, the TreasureIsland extraction could be a separate issue, or at the very least separate commits.

2023-12-07 13:50 UTC, JoXW100 commented
> Just want to add that some of the changes here could have been made into their own pull requests since this one is very large (42 files changed). For example, the TreasureIsland extraction could be a separate issue, or at the very least separate commits.

I agree with you and have made this draft into a pr for general improvements as the actual combat elements are yet to be implemented. The combat implementation itself will follow in a separate pr.

2023-12-07 17:20 UTC, joelsiks requested changes
See comments. You proably forgot to update the doc comment for `Scene::BuildNavMesh`. Otherwise good stuff. I've tried running and it seems to work fine. I have a few small things that would be easiest to show later, but it relates to moving ship(s).

2023-12-07 19:18 UTC, JoXW100 commented on src/engine/IDisplayLayer.hpp
> +    inline const QuadTree &GetQuadTree() const { return m_quadtree; }
That is why a `const` reference is returned, it cannot be altered.

2023-12-08 13:04 UTC, caspernorrbin approved these changes

2023-12-08 13:15 UTC, joelsiks commented on src/engine/Scene.cpp
> +    float *grid = new float[gridSize];
Sure, was just that it is named costs in the function it is passed to.

2023-12-08 13:18 UTC, joelsiks commented
Good stuff

2023-12-08 13:18 UTC, joelsiks approved these changes
Good stuff!

2023-12-08 13:19 UTC, merged