MVP Help menu
joelsiks/admirals pull request #148
Opened 2023-12-19 15:06 UTC by caspernorrbin

Added a help menu to the MVP with some game instructions, it looks like this:

![image](https://github.com/joelsiks/admirals/assets/61315185/75b4304c-1547-4333-8b26-d89d08ff3c84)

One issue with this is that the font is very large, so it's not possible to fit a lot of text on one line. As a result, the instructions are brief and done with very short sentences. I tried longer multi-line instructions but that looked even worse.

I am very open to changing the actual text to be more informative if you have any ideas.

2023-12-20 08:58 UTC, JoXW100 reviewed
Much of the text could be made much clearer, like "Islands give extra gold" to "Islands give extra gold for each ship next to it". 
Does the `TextOption` element support newline characters? If not, we should add this support.
Similarly we should add a text scale argument to the `TextOption` element constructor.

2023-12-20 13:11 UTC, caspernorrbin commented
> Much of the text could be made much clearer, like "Islands give extra gold" to "Islands give extra gold for each ship next to it". Does the `TextOption` element support newline characters? If not, we should add this support. Similarly we should add a text scale argument to the `TextOption` element constructor.

I changed the sentence to "Place ships by islands for bonus gold.", as yours would not fit.
Newlines do not function as expected with `TextOption`s, and although I briefly explored scaling, there were issues with position and orientation. Rectifying these concerns goes beyond the scope of this current pull request. Implementing support for scalable menus is a broader task that requires more time and attention.

2023-12-21 13:23 UTC, JoXW100 requested changes
During testing i found one issue that needs to be addressed. It is possible to click multiple menu buttons at once since they do not mark the event as "handled". This opens the manus above eachoter. In the menu button `onCLick` event handlers, please set the `handled` flag to true to prevent this.

2023-12-21 15:03 UTC, JoXW100 approved these changes

2023-12-21 15:04 UTC, merged