Engine context with DeltaTime
joelsiks/admirals pull request #67
Opened 2023-11-23 19:39 UTC by caspernorrbin

Adds the `Context` class as part of the engine. With this, the renderer context has been removed and its contents placed in Context. The renderer and the render functions (including all implemented objects) have been modified to reflect this.

Additionally, the context is now included in both `OnStart()` and `OnUpdate()` to allow for them to use it. At the moment only `DeltaTime` is implemented, but more can be added to it in the future if we see fit.

The menu and gameObject test have been modified to use DeltaTime from the context

2023-11-24 08:57 UTC, JoXW100 requested changes
This implementation has many issues that will need to be considered, mainly to do with how the value of the context is passed around and modified.

When passing around the `Context` outside `Engine`, it should always be a const reference to disallow modifying it outside the engine. This means that the window size in the context will need to be updated in the `Engine` and not the `Renderer`. There should then be no need to store a `Context` as a pointer inside `Engine`. 

I would also want to handle calculating `DeltaTime` in `Engine` instead of `Context` as i imagine the `Context` just to be a holder of data (we can discuss this). 

Lastly, you have to remove the old `RendererContext` struct from `IDrawable.hpp`.

2023-11-24 09:00 UTC, joelsiks reviewed
See specific comments.

There are a lot of `OnStart()`/`OnUpdate()` calls made without a const reference to the Context that should be made into a const reference. This will be solved if the definitions of `OnStart()`/`OnUpdate()` are changed in `GameObjects.hpp`.

2023-11-24 09:04 UTC, JoXW100 commented on src/engine/Context.hpp
> +    bool renderDebugOutlines;
that would break the menu option to toggle debug lines.

2023-11-24 12:20 UTC, joelsiks commented on src/engine/Context.hpp
> +    bool renderDebugOutlines;
true

2023-11-24 12:31 UTC, joelsiks commented
EngineContext should be made into a data-only struct. All updates to the context should be made from the Engine.
`GetContext()` inside the Engine should return a const reference to the context inside the engine. Also, all places that use the context inside the engine (i.e calls to OnUpdate/OnStart/Render etc..) should use `GetContext` for "safety".

2023-11-24 13:43 UTC, caspernorrbin commented
`EngineContext` is now a data only struct and only the Engine can make updates. Start/Update/Render has been changed to use a const reference. As only the engine should be allowed to edit the context, the deltaTime functionality and updating window size has been moved to the game loop of the engine

2023-11-25 12:19 UTC, JoXW100 requested changes
Some minor fixes are needed. If we want to store the window size as a Vector2, some additional refactoring will be needed. Try to fix the clang warnings in the modified files.

2023-11-27 11:34 UTC, JoXW100 approved these changes

2023-11-27 11:40 UTC, merged